stages:
  get_preprint_data_medrxiv:
    cmd: python preprint_revisions/get_preprint_data.py --start_date 2020-01-01 --end_date 2022-10-31 --filename "extracted_medrxiv.json" --server "medrxiv"
    deps:
    - preprint_revisions/get_preprint_data.py
    outs:
    - data/extracted_medrxiv.json

  get_preprint_data_biorxiv:
    cmd: python preprint_revisions/get_preprint_data.py --start_date 2020-01-01 --end_date 2022-10-31 --filename "extracted_biorxiv.json" --server "biorxiv"
    deps:
    - preprint_revisions/get_preprint_data.py
    outs:
    - data/extracted_biorxiv.json
    
  get_revisions_medrxiv:
    cmd: python preprint_revisions/get_revisions.py --server "medrxiv"
    deps: 
    - preprint_revisions/get_revisions.py
    - data/extracted_medrxiv.json
    - data/medrxiv_urls.json
    outs:
    - data/revision_dict_medrxiv.json

  get_revisions_biorxiv:
    cmd: python preprint_revisions/get_revisions.py --server "biorxiv"
    deps: 
    - preprint_revisions/get_revisions.py
    - data/extracted_biorxiv.json
    - data/biorxiv_urls.json
    outs:
    - data/revision_dict_biorxiv.json

  get_revision_times_medrxiv:
    cmd: python preprint_revisions/revision_time.py --server "medrxiv"
    deps: 
    - preprint_revisions/revision_time.py
    - data/extracted_medrxiv.json
    outs:
    - data/proportion_revisions_biorxiv.png
    - data/revisions_over_time_biorxiv.png
    - data/revision_times_biorxiv.png
    - data/number_of_revisions_biorxiv.png
    - data/revision_times_biorxiv_most_revised.png
    - data/revision_traces_biorxiv.json

  get_revision_times_biorxiv:
    cmd: python preprint_revisions/revision_time.py --server "biorxiv"
    deps: 
    - preprint_revisions/revision_time.py
    - data/extracted_medrxiv.json
    outs:
    - data/proportion_revisions_medrxiv.png
    - data/revisions_over_time_medrxiv.png
    - data/revision_times_medrxiv.png
    - data/number_of_revisions_medrxiv.png
    - data/revision_times_medrxiv_most_revised.png
    - data/revision_traces_medrxiv.json

  get_revision_stats_medrxiv:
    cmd: python preprint_revisions/revision_text_statistics.py --server "medrxiv"
    deps: 
    - preprint_revisions/revision_text_statistics.py
    - data/revision_dict_medrxiv.json
    - data/extracted_medrxiv.json
    outs:
    - data/proportion_revisions_with_text_medrxiv.png
    - data/revision_text_statistics_medrxiv.png

  get_revision_stats_biorxiv:
    cmd: python preprint_revisions/revision_text_statistics.py --server "biorxiv"
    deps: 
    - preprint_revisions/revision_text_statistics.py
    - data/revision_dict_biorxiv.json
    - data/extracted_biorxiv.json
    outs:
    - data/proportion_revisions_with_text_biorxiv.png
    - data/revision_text_statistics_biorxiv.png

  cluster_medrxiv:
    cmd: python preprint_revisions/cluster.py --server "medrxiv"
    deps:
    - preprint_revisions/cluster.py
    - data/revision_dict_medrxiv.json
    outs:
    - data/clusters_medrxiv.png
    - data/cluster_dict_medrxiv.json

  cluster_biorxiv:
    cmd: python preprint_revisions/cluster.py --server "biorxiv"
    deps:
    - preprint_revisions/cluster.py
    - data/revision_dict_biorxiv.json
    outs:
    - data/clusters_biorxiv.png
    - data/cluster_dict_biorxiv.json