stages:
  get_preprint_data_medrxiv:
    cmd: python preprint_revisions/get_preprint_data.py --start_date 2022-01-01 --end_date 2022-02-01 --filename "extracted_medrxiv.json" --server "medrxiv"
    deps:
    - preprint_revisions/get_preprint_data.py
    outs:
    - data/extracted_medrxiv.json

  get_revisions_medrxiv:
    cmd: python preprint_revisions/get_revisions.py --preprint-data-file "extracted_medrxiv.json"
    deps:
    - preprint_revisions/get_revisions.py
    - data/extracted_medrxiv.json
    - data/medrxiv_urls.json
    outs:
    - data/revision_dict_medrxiv.json

  get_revision_times_medrxiv:
    cmd: python preprint_revisions/revision_time.py --server "medrxiv"
    deps:
    - preprint_revisions/revision_time.py
    - data/extracted_medrxiv.json
    outs:
    - results/proportion_revisions_medrxiv.png
    - results/revisions_over_time_medrxiv.png
    - results/revision_times_medrxiv.png
    - results/number_of_revisions_medrxiv.png
    - results/revision_times_medrxiv_most_revised.png
    - results/revision_traces_medrxiv.json

  get_revision_stats_medrxiv:
    cmd: python preprint_revisions/revision_text_statistics.py --server "medrxiv"
    deps:
    - preprint_revisions/revision_text_statistics.py
    - data/revision_dict_medrxiv.json
    - data/extracted_medrxiv.json
    outs:
    - results/proportion_revisions_with_text_medrxiv.png
    - results/revision_text_statistics_medrxiv.png
    - data/merged_df_medrxiv.csv

  cluster_medrxiv:
    cmd: python preprint_revisions/cluster.py --server "medrxiv"
    deps:
    - preprint_revisions/cluster.py
    - data/revision_dict_medrxiv.json
    outs:
    - data/clusters_medrxiv.png
    - data/cluster_dict_medrxiv.json
